"""Byter book_id till story_id i Scene

Revision ID: dba7aaf45347
Revises: fc72d724bc37
Create Date: 2025-01-28 14:43:58.540074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dba7aaf45347'
down_revision = 'fc72d724bc37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scene', schema=None) as batch_op:
        batch_op.add_column(sa.Column('story_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_scene_story_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_scene_story_id', 'story', ['story_id'], ['id'])
        batch_op.drop_column('book_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scene', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_scene_story_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_scene_story_id', 'story', ['book_id'], ['id'])
        batch_op.drop_column('story_id')

    # ### end Alembic commands ###
