"""Skapa ny databasstruktur

Revision ID: ebf3f384fc63
Revises: 
Create Date: 2025-01-12 01:39:50.680720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebf3f384fc63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('stripe_account_id', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('stripe_account_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('promo_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uq_code', sa.String(length=50), nullable=False),
    sa.Column('discount', sa.Integer(), nullable=False),
    sa.Column('uses', sa.Integer(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_indefinite', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_promo_codes_user_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uq_code')
    )
    op.create_table('story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('child_gender', sa.String(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('story_text', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.String(), nullable=True),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.Column('text_url', sa.String(), nullable=True),
    sa.Column('omslag_image_url', sa.String(), nullable=True),
    sa.Column('insida_image_urls', sa.JSON(), nullable=True),
    sa.Column('image_urls', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_story_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promo_code_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('promo_code_id', sa.Integer(), nullable=False),
    sa.Column('tier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_codes.id'], name='fk_promo_code_usage_promo_code_id'),
    sa.ForeignKeyConstraint(['tier_id'], ['tiers.id'], name='fk_promo_code_usage_tier_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_promo_code_usage_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promo_code_usage')
    op.drop_table('story')
    op.drop_table('promo_codes')
    op.drop_table('user')
    op.drop_table('tiers')
    # ### end Alembic commands ###
