"""Lägg till Scene-tabell för att lagra berättelsens scener

Revision ID: fc72d724bc37
Revises: ebf3f384fc63
Create Date: 2025-01-28 13:46:20.860745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc72d724bc37'
down_revision = 'ebf3f384fc63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scene',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('avatar', sa.String(), nullable=False),
    sa.Column('situation', sa.String(), nullable=False),
    sa.Column('background', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['story.id'], name='fk_scene_story_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('promo_code_usage', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_promo_code_usage_promo_code_id', 'promo_codes', ['promo_code_id'], ['id'])
        batch_op.create_foreign_key('fk_promo_code_usage_tier_id', 'tiers', ['tier_id'], ['id'])
        batch_op.create_foreign_key('fk_promo_code_usage_user_id', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promo_code_usage', schema=None) as batch_op:
        batch_op.drop_constraint('fk_promo_code_usage_user_id', type_='foreignkey')
        batch_op.drop_constraint('fk_promo_code_usage_tier_id', type_='foreignkey')
        batch_op.drop_constraint('fk_promo_code_usage_promo_code_id', type_='foreignkey')
        batch_op.alter_column('user_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.drop_table('scene')
    # ### end Alembic commands ###
